input: ./test.gpkg
output: ./test-inds.gpkg
datadir: ./data
batchsize: 5
options:
  overwrite: false
  maxcores: 1
  progress: true
resources:
  get_gfw_treecover:
    args:
      version: GFC-2023-v1.11
  get_gfw_lossyear:
    args: 
      version: GFC-2023-v1.11
indicators:
  calc_treecover_area:
    args: 
      min_cover: 30
      min_size: 1
    options:
      chunksize: 50000
